[package]
name = "recipe-lang"
version = "0.1.0"
edition = "2021"
description = "Write recipes in a human readable and machine parseable language"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
rstest = "0.17.0"
serde_json = "1.0"

[lib]
path = "src/lib.rs"
