name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Update Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile
      - name: Commit and push Cargo.lock
        run: |
          ls -l .git/COMMIT_EDITMSG
          rm -rf .git/COMMIT_EDITMSG
          git ls-files --stage
          git config --global --add safe.directory "*"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Cargo.lock
          git commit -m 'ci: update Cargo.lock'
          git push